apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
     "krateo.io/connector-verbose": "true"
  name: crif-composition-usecase1
  namespace: demo-system
spec:
  chart:
    url: https://github.com/stefanoc1996/example-chart/raw/main/crif-usecase1-0.0.22.tgz

    
